

name: Build and Push Docker Image

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  build_docker_images:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: Get the release version
      id: strip-branch-name
      run: |
        release_version=$(echo "${{ steps.previoustag.outputs.tag }}" | sed 's/v//g')
        echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
      shell: bash
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push latest
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

    - name: Build and push release
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

    # - name: Inspect
    #   run: |
    #     docker image inspect ${{ env.DOCKER_IMAGE_NAME }}:latest  

