

name: Build and Push Docker Image to Docker Hub

on:
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action when I create or push a `release/**` branch
  # push:
  #   branches:
  #     - main

# env:
#   # Use docker.io for Docker Hub if empty
#   REGISTRY: docker.io
#   # github.repository as <account>/<repo>
#   IMAGE_NAME: ${{ github.repository }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker-compose build --no-cache --force-rm 
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Test the Docker image
#         run: docker-compose up -d 
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USER }}
#           password: ${{ secrets.DOCKER_TOKEN }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: "{{defaultContext}}"
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}

env:
  DOCKER_IMAGE_NAME: ${{ github.repository }}
  DOCKER_REGISTRY_URL: docker.io

jobs:
  build_docker_images:
    # Job name that shows in the GitHub UI
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      # with:
      #   fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
        #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional
    - name: Get the release version
      id: strip-branch-name
      run: |
        release_version=$(echo "${{ steps.previoustag.outputs.tag }}" | sed 's/v//')
        echo "RELEASE_VERSION=${{ steps.previoustag.outputs.tag }}" >> $GITHUB_ENV
      shell: bash

    # - name: Dump env
    #   run: env | sort
    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: echo "$GITHUB_CONTEXT"

    # - name: Get the release version
    #   # i.e.: release/1.0.0 -> 1.0.0
    #   id: strip-branch-name
    #   run: |
    #     release_version=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/.*\///')
    #     echo "Building 1 release version $release_version"
    #     release_version=$(echo "${{ github.event.release.tag_name }}")
    #     echo "Building 2 release version $release_version"
    #     echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
    #   shell: bash

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag $DOCKER_IMAGE_NAME:$RELEASE_VERSION
      # run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:$RELEASE_VERSION

    # Tag the Docker Images
    - name: Tag the image for the private registry $DOCKER_REGISTRY_URL
      run: docker tag $DOCKER_IMAGE_NAME:$RELEASE_VERSION $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:$RELEASE_VERSION

    - name: Create a latest image as well
      run: docker tag $DOCKER_IMAGE_NAME:$RELEASE_VERSION $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

    # Push the images to the registry
    - name: Push the Docker image with version number
      run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:$RELEASE_VERSION

    - name: Push the latest tag
      run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

    # Remove the local images
    - name: Remove the Docker image with version number
      run: docker rmi $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:$RELEASE_VERSION

    - name: Remove the Docker image with latest tag
      run: docker rmi $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

    - name: Remove the local image
      run: docker rmi $DOCKER_IMAGE_NAME:$RELEASE_VERSION

    - name: Prune Docker
      run: docker system prune -a -f