name: Sync Fork

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          owner: pebalk
          base: main
          head: main